#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : kbproto
Version  : 1.0.7
Release  : 7
URL      : http://xorg.freedesktop.org/releases/individual/proto/kbproto-1.0.7.tar.bz2
Source0  : http://xorg.freedesktop.org/releases/individual/proto/kbproto-1.0.7.tar.bz2
Summary  : KB extension headers
Group    : Development/Tools
License  : HPND
Requires: kbproto-doc
BuildRequires : libxslt-bin
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : xmlto

%description
X Keyboard Extension
This extension defines a protcol to provide a number of new capabilities
and controls for text keyboards.

%package dev
Summary: dev components for the kbproto package.
Group: Development

%description dev
dev components for the kbproto package.


%package doc
Summary: doc components for the kbproto package.
Group: Documentation

%description doc
doc components for the kbproto package.


%prep
%setup -q -n kbproto-1.0.7

%build
%configure --disable-static
make V=1 %{?_smp_mflags}

%check
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/XKB.h
/usr/include/X11/extensions/XKBgeom.h
/usr/include/X11/extensions/XKBproto.h
/usr/include/X11/extensions/XKBsrv.h
/usr/include/X11/extensions/XKBstr.h
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/kbproto/*
